### ISSUE TITLE
setup.sh - not create user vaultwarden if not exist

### ISSUE THREAD

**Issue by laweschan** [vpolaris/Podman-Bitwarden#17]
**Describe the bug**
As Title

**To Reproduce**
git clone https://github.com/vpolaris/Podman-Bitwarden.git
cd Podman-Bitwarden
chmod u+x setup.sh; sudo ./setup.sh

**Expected behavior**
script will auto create user if not exists

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Fedora
 - Version 34

**Additional context**
add command "groupadd docker"  before this line:
useradd -m -u 10502 -G docker --shell /bin/bash --comment "Vaultwarden RS User Container" --user-group vaultwarden

then it should able to continues

**Comment by vpolaris** [comment]
I adding a test to check docker group and create it if missing,

    if [[ "$(getent group docker)"!="" ]];then 
        printf "group docker exists\n"
    else
        groupadd docker
    fi

thank you for your support
