### ISSUE TITLE
building error - serveur-status.conf": no such file or directory

### ISSUE THREAD

**Issue by laweschan** [vpolaris/Podman-Bitwarden#18]
**Describe the bug**
While building image, an error occurs about missing file

**To Reproduce**
git clone https://github.com/vpolaris/Podman-Bitwarden.git
cd Podman-Bitwarden
chmod u+x setup.sh; sudo ./setup.sh

**Expected behavior**

**Screenshots**
![image](https://user-images.githubusercontent.com/17445193/145188433-f5151d70-9f8d-45cd-8982-bf3d22e86519.png)

**Desktop (please complete the following information):**
 - OS: Fedora
 - Version 34

**Additional context**
![image](https://user-images.githubusercontent.com/17445193/145188543-290179d7-4dc9-4505-927e-337128a93657.png)
source folder doesn't create any file refer to serveur-status.conf, thus copy task error

**Comment by vpolaris** [comment]
Hi, my bad
I added missing file 

FYI, it's not in use at this time. I plan to do some health checks through this server conf

Thank you four your feedback
